### ISSUE TITLE
Double Title on "How it works" (And Congratulations)

### ISSUE THREAD

**Issue by crubier** [remorses/landing-blocks#2]
Hi, first congratulations, this package is awesome! I did a few landing pages with it in the last few days and I'm in love! Simple and effective, as should be!

I have just one small problem, which is the duplication of step titles in How It Works sections:

![Screenshot 2020-06-09 at 09 29 07](https://user-images.githubusercontent.com/2954572/84125085-f34a2c80-aa33-11ea-919a-e7a7031717b6.jpg)

Is it in purpose? I did not notice it at first to be honest, until I added longer titles, which did not look good.

**Comment by remorses** [comment]
Yes I copied the https://prismic.io site for that part, the double title makes it look more sophisticated

Longer titles should be truncated, I will check that

If you have any suggestion on alternative design please share

**Comment by crubier** [comment]
On Prismic it is not exactly the same title in both cases.

![Screenshot 2020-06-09 at 10 08 25](https://user-images.githubusercontent.com/2954572/84128989-3955bf00-aa39-11ea-9cc0-916fb57ffcca.jpg)

 Having an exact duplicate in all cases is not as good

**Comment by remorses** [comment]
I will add a a prop for that, do you have a good name?

**Comment by remorses** [comment]
Maybe decorativeHeading?
